# Generated by Django 4.0.3 on 2022-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num1',
            field=models.BigIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='num2',
            field=models.BigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
